// MainActivity — client entry point.
//
// Binds to CalculatorService (running in a separate process).
// The IBinder received in onServiceConnected is actually a Proxy object
// auto-generated by the AIDL compiler. Calling proxy.add() does NOT
// directly invoke our implementation — it:
//   1. Writes arguments into a Parcel
//   2. Sends a Binder transaction through /dev/binder
//   3. Kernel driver copies data into the service process
//   4. Stub.onTransact() dispatches to the real method
//   5. Result flows back the same way in reverse
//
// THREADING NOTE — Binder calls from the main thread:
//   Every AIDL method call is synchronous — the calling thread blocks
//   until the remote method returns. When called from the UI (main) thread,
//   the UI freezes for the duration. In this project, divide() has an
//   artificial 2-second Thread.sleep() to make this visible.
//
//   To verify: tap Divide with A=10, B=2. The UI freezes for ~2 seconds,
//   then "10 divide 2 = 5" appears. Meanwhile the service log shows:
//     "divide(10, 2) called on thread: Binder:xxx"
//   This proves the service runs on a Binder thread pool thread (not its
//   main thread), but the client's main thread still blocks waiting.
//
//   Fix without Coroutines/RxJava (which are excluded by project constraints):
//     Thread {
//         try {
//             val result = service.divide(a, b)
//             runOnUiThread { binding.resultText.text = "$a / $b = $result" }
//         } catch (e: RemoteException) {
//             runOnUiThread { binding.resultText.text = "Error: ${e.message}" }
//         }
//     }.start()
//
//   In real apps, the Binder call would be offloaded to a background thread.
//   For this simple project, we call from the main thread deliberately to
//   demonstrate the blocking behavior.

package com.izzatismail.binderlearning

import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.ServiceConnection
import android.os.Bundle
import android.os.IBinder
import android.os.RemoteException
import android.util.Log
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.izzatismail.binderlearning.databinding.ActivityMainBinding
import com.izzatismail.binderlearning.service.CalculatorService

private const val TAG = "CalculatorClient"

class MainActivity : AppCompatActivity() {

    private var calculatorService: ICalculatorService? = null
    private lateinit var binding: ActivityMainBinding

    private val connection = object : ServiceConnection {
        // onServiceConnected receives an IBinder — the Binder token that the
        // Service returned from onBind(). In this process, this IBinder is an
        // ICalculatorService.Proxy that wraps a remote reference to the Stub
        // in the service process. Every method call on it goes through Binder IPC.
        //
        // DEATH HANDLING NOTE — linkToDeath:
        //   If the service process crashes, onServiceDisconnected fires but there
        //   is a race: AIDL calls sent before the kernel notifies us will throw
        //   RemoteException. Production code can register with
        //     serviceIBinder.linkToDeath(deathRecipient, flags)
        //   to get an immediate callback via binderDied() when the remote process
        //   dies, without waiting for the AMS to dispatch onServiceDisconnected.
        //   This is how CarService detects a crashed VHAL HAL without polling.
        override fun onServiceConnected(name: ComponentName?, service: IBinder?) {
            Log.d(TAG, "Service connected: $name")
            calculatorService = ICalculatorService.Stub.asInterface(service)
            binding.connectionStatus.text = "Service Connected"
            enableButtons(true)
        }

        // onServiceDisconnected is called when the service process crashes or is killed.
        // This is where RemoteException originates in real scenarios.
        override fun onServiceDisconnected(name: ComponentName?) {
            Log.d(TAG, "Service disconnected: $name")
            calculatorService = null
            binding.connectionStatus.text = "Service Disconnected"
            enableButtons(false)
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        binding.btnAdd.setOnClickListener { performOperation("add") }
        binding.btnSubtract.setOnClickListener { performOperation("subtract") }
        binding.btnMultiply.setOnClickListener { performOperation("multiply") }
        binding.btnDivide.setOnClickListener { performOperation("divide") }
    }

    override fun onStart() {
        super.onStart()
        // Bind to the service. Since both modules are in the same APK,
        // we can use an explicit Intent referencing the Service class directly.
        val intent = Intent(this, CalculatorService::class.java)
        bindService(intent, connection, Context.BIND_AUTO_CREATE)
        Log.d(TAG, "Binding to CalculatorService...")
    }

    override fun onStop() {
        super.onStop()
        if (calculatorService != null) {
            unbindService(connection)
            calculatorService = null
            Log.d(TAG, "Unbound from CalculatorService")
        }
    }

    private fun enableButtons(enabled: Boolean) {
        binding.btnAdd.isEnabled = enabled
        binding.btnSubtract.isEnabled = enabled
        binding.btnMultiply.isEnabled = enabled
        binding.btnDivide.isEnabled = enabled
    }

    private fun performOperation(op: String) {
        val a = binding.inputA.text.toString().toIntOrNull() ?: return
        val b = binding.inputB.text.toString().toIntOrNull() ?: return
        val service = calculatorService

        if (service == null) {
            binding.resultText.text = "Error: Not connected"
            return
        }

        try {
            // Every AIDL proxy method can throw RemoteException.
            // The call blocks the current thread until the Binder transaction
            // completes — if called from main thread, the UI freezes.
            // Real apps should call from a background thread.
            val result = when (op) {
                "add" -> service.add(a, b)
                "subtract" -> service.subtract(a, b)
                "multiply" -> service.multiply(a, b)
                "divide" -> service.divide(a, b)
                else -> throw IllegalArgumentException("Unknown op: $op")
            }
            binding.resultText.text = "$a $op $b = $result"
            Log.d(TAG, "$a $op $b = $result")
        } catch (e: RemoteException) {
            // RemoteException means the Binder transaction itself failed:
            // service process crashed, was killed by LMK, network error, etc.
            Log.e(TAG, "RemoteException during $op($a, $b)", e)
            binding.resultText.text = "Remote error: ${e.message}"
        }
    }
}